### ISSUE TITLE
Dismount Error

### ISSUE THREAD

**Issue by ectocooler** [alishahb/HBProducts#1]
label:@FishingMaster
label: bug
[10856 2017-06-11 09.25.txt](https://github.com/alishahb/HBProducts/files/1066646/10856.2017-06-11.09.25.txt)

Fishing Master has an error where it repeatedly dismounts, thinking it is on a water mount. This only appeared after receiving the water walking buff on the Underlight Angler

It repeatedly does this action on both land and water. This may not be just the water walking buff.

**Comment by O-n-y** [comment]
this should be fixed on upcoming release build 6.1.167.2020, let me know if you still have issue on this build, after it get approve via HB Team.

**Comment by alishahb** [comment]
This issue should be fixed on upcoming release build 6.1.167.2020. Currently it's awaiting approval via HB Core Team. 
If you still have issue on new build, open new issue ticket, with log attached. Bot should be stopped right after issue occur.
