### ISSUE TITLE
@TreasureHunter Feature Request - Kick Offline players

### ISSUE THREAD

**Issue by kxy1983s** [alishahb/HBProducts#3]
Discord Beta team - Zumoto#4764 -Please add an option in Nethershard farming in groups to kick players that have been offline for more than 5 minutes, this gives new players a chance to join group. The 5 minute delay is preferable to instant kick, because sometimes players accidentally disconnect and instant kick would look bot-like.

**Comment by alishahb** [comment]
implemented
