### ISSUE TITLE
@Treasure Hunter - Nethershards Feature Request - Option to put epic loot in Bank

### ISSUE THREAD

**Issue by kxy1983s** [alishahb/HBProducts#4]
While Nethershard farming, the character collects a lot of Soulbound Epic gear from Dauntless tokens. This quickly fills the bags up. Please add option to hearth to Dalaran and store epic soulbound gear thats not equipped into bank. 

Player can later remove them from the bank for Disenchant.

This allows character to keep farming instead of stopping for bags full.

**Comment by O-n-y** [comment]
This is out of product purpose, for bank interaction i have in separate work product, however no eta as usual.

**Comment by alishahb** [comment]
This is out of product purpose. For bank interaction (As guild bank as personal bank) there is separate product in work. However no eta if / when it will be available.
